### ISSUE TITLE
Bot reports wrong user count.

### ISSUE THREAD

**Issue by belohnung** [nimarion/promcord#116]
## General Troubleshooting

  
- [x] I have checked for similar issues.
- [x] I have updated to the latest promcord version
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

The Bot reports a wrong user count.
![image](https://user-images.githubusercontent.com/35181949/105025545-bfb19500-5a4d-11eb-98aa-0b3429763bcc.png)

### Expected Behavior

The bot should report the right user count.
![image](https://user-images.githubusercontent.com/35181949/105025599-d5bf5580-5a4d-11eb-8ef4-68bd519d5dc2.png)

### Exception or Error

N/A

**Comment by nimarion** [comment]
Propably a discord related issue. Cant reproduce.
