### ISSUE TITLE
Can I use it for multiple discord server?

### ISSUE THREAD

**Issue by FoxyWhite2541** [nimarion/promcord#130]
Hello. 

I would like to use this for a couple of my servers. Now, I can see it is tracking both of my servers but is it possible to set it, so on one dashboard, it tracks one server and on another one, it tracks a different one?

Also, instead of reading server ID, could it be possible, to have it be named? Like instead of showing 18 numbers, it would show server name? Same for the users.

**Comment by nimarion** [comment]
Yes promcord supports multible servers per default. You should be able to select them in the dropdown menu in grafana. 
Currently it is not possible to link the ids to the real user or server names because grafana does not support it :/

**Comment by FoxyWhite2541** [comment]
Hi Marion. 

Thank you for the answer. Do you maybe know, if it is possible to lock one server per dashboard? 

So in this case, if I'm in 2 servers, I would potentially have 2 dashboards and I don't want others to see the other server. 

Like Team A shouldn't be able to see Team B server and stats.

**Comment by nimarion** [comment]
You could replace guild with the id of the server in every query or create a variable in the dashboard settings so you can better reuse it.
This article might help a bit https://blog.timescale.com/blog/grafana-variables-101/
![image](https://user-images.githubusercontent.com/23435250/115365592-d094b280-a1c4-11eb-921c-c7dd0468a809.png)

**Comment by FoxyWhite2541** [comment]
Lovely. Cheers for a quick response :D
