### ISSUE TITLE
Prefix metric names with `promcord_`

### ISSUE THREAD

**Issue by ChipWolf** [nimarion/promcord#131]
## Feature Request

It'd be ideal if the metrics could all start with `promcord_` so they can be easily found in a large list of metrics & to avoid any duplicates, for example; `msg_count` was already in use by another one of our sources.

**Comment by nimarion** [comment]
Sounds like a good idea. What do you think about an optional environment variable like PROMCORD_PREFIX?

**Comment by ChipWolf** [comment]
Assuming you'll set the default prefix to `promcord`, it'll have to be a major (breaking) version bump.
The benefit of exposing a variable would be allowing the change to be backwards compatible with existing dashboards if people null the variable.
However, I'd probably use the major version bump as an opportunity not to worry about backwards compatibility; I don't know of another prometheus exporter with a configurable prefix so likely not worth the additional effort.

**Comment by nimarion** [comment]
My idea was that the default prefix would be null. So experienced users could change it if they want

**Comment by ChipWolf** [comment]
Totally up to you. I would set it as the default just to match the majority of other metrics sources, not entirely necessary though

![](https://i.cwlf.uk/P2xXm)
