### ISSUE TITLE
Resolve & cache username/display names

### ISSUE THREAD

**Issue by ChipWolf** [nimarion/promcord#133]
## Feature Request

We could make the dashboards easier to parse through if the user IDs were resolved to display names and usernames which could be bundled into the metrics.
I'm aware this would come at a significant API quota cost, and potentially would require some caching & persistence, so it should be opt-in.

**Comment by nimarion** [comment]
I’ll take a look at it. For me it would be better if Grafana could map the user and server IDs to the real names via a simple rest api. I already had a look at this topic a while ago but could not figure out a good way to achieve this. 
Opt in sounds good if there is no better solution 👍

**Comment by ChipWolf** [comment]
A Grafana app is possible if you would like to develop custom panels for this; personally, I reckon it should be handled by this project to avoid additional overhead.

**Comment by nimarion** [comment]
So you would also store the username as a new label for each metric?

**Comment by ChipWolf** [comment]
I think that would be ideal, it'd be easier to work with on a dashboard.

**Comment by rssnyder** [comment]
I just opened https://github.com/nimarion/promcord/pull/139 which solved some of my issues with wanting user/channel names, to stop having to look up user IDs.
